version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile   
    ports:
      - "80:80"
    environment:
      - URL=https://www.booli.se
    volumes:
      - ./code:/app/code