version: "3.9"
    
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ocn217
      MYSQL_DATABASE: ubuntu
      MYSQL_PASSWORD: ocn217
      MYSQL_USER: chris
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db: