version: '3'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_HOST=127.0.0.1
      - MYSQL_ROOT_PASSWORD=dockers
      - MYSQL_DATABASE=caliente
      - MYSQL_USER=chris
      - MYSQL_PASSWORD=docker
    volumes:
       - ./seed:/docker-entrypoint-initdb.d
  
  adminer:
      image: adminer
      restart: always
      ports:
          - 8080:8080
      