version: '3'
services:
  db:
    image: mysql
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ocn217
      MYSQL_DATABASE: caliente
      MYSQL_USER: chris
      MYSQL_PASSWORD: ocn217
    command: --default-authentication-plugin=mysql_native_password
    volumes:
       - ./seed:/docker-entrypoint-initdb.d